### ISSUE TITLE
增加: dictutil.merge(dst, *others, mode=None) 合并多个dictionary

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#114]
- 合并时 直接修改dst.

- others 必须都是dict或子类.

- mode=("keep"|"replace"|"merge"|"forcemerge") 来指定others[i]的key已经存在dst中时的行为: keep保留dst的key. replace直接替换dst中的key. merge或forcemerge来递归的用others[i]中的key 合并覆盖 dst的key. 要求只有dict可以互相合并. 对forcemerge, 如果dst[key]不是字典直接用others[i][key] 替换. 对merge, 抛出异常.

**Comment by 13yu** [comment]
应该可以通过对每个other循环调用conbineto来实现吧，combineto的第三个参数op，传入一个自定义的函数

**Comment by drmingdrmer** [comment]
这个可以去掉了吗?

**Comment by 13yu** [comment]
哪个？，这个issue吗，需要包装一个merge函数吗，这个merge函数使用combineto实现？

**Comment by drmingdrmer** [comment]
如果有combine了就不加merge了啊...

**Comment by 13yu** [comment]
哦
