### ISSUE TITLE
IP地址转int，int转IP地址

### ISSUE THREAD

**Issue by liubaohai** [bsc-s2/pykit#182]
任务队列中有用到。task表中开始设计的consumer_id是个bigint类型，开发的时候想着这个字段保存consumer的ip方便debug，就这样做了一个转化

**Comment by drmingdrmer** [comment]
这个会用在哪里来?

**Comment by liubaohai** [comment]
@drmingdrmer 任务队列中有用到。task表中开始设计的consumer_id是个bigint类型，开发的时候想着这个字段保存consumer的ip方便debug，就这样做了一个转化。

**Comment by drmingdrmer** [comment]
#183 @liubaohai 看看这个. 看你那能用起来不, 或者是否可以交给程洋来整合到你的代码里.

**Comment by liubaohai** [comment]
@drmingdrmer 可以用，只有两三个地方要改，我告诉下程洋在哪里。到时候改好我review下，然后测下，应该可以的。

**Comment by drmingdrmer** [comment]
@godgitgold 可关否?

**Comment by godgitgold** [comment]
@drmingdrmer  s2已经用到ip转换的地方都替换成了ip_to_num 和 num_to_ip。但是没有测试

**Comment by drmingdrmer** [comment]
这个项目里这个功能就可以关了
