### ISSUE TITLE
dictutil.combineto 缺少测试.

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#198]
先测底层函数. 上层可以酌情省略一些.

add函数的测试里缺少一种情况, a中没有某个key, b中有某个key时,对`b[k]`做深度copy. 这个行为没能测试到.

**Comment by drmingdrmer** [comment]
这块的深度copy也不确定你是怎么考虑的. 感觉行为会有非预期的结果. 用测试约束好结果行为.

**Comment by 13yu** [comment]
深度copy应该是为了保证b的内容在后面不会有被修改的风险，如果没有深度copy，后面对a的修改就会反映到b上，因为都引用同一个对象

**Comment by drmingdrmer** [comment]
唔...明白了

**Comment by drmingdrmer** [comment]
@13yu 有个问题啊...combineto 什么时候需要 非recursive的调用? 有场景吗?

**Comment by 13yu** [comment]
有时候b中可能会包含一些不确定的又不希望累加的字典类型的字段，比如:
a: {'cont': 0}
b: {'cout': 100, 'foo': {...}}

**Comment by drmingdrmer** [comment]
唔...
