### ISSUE TITLE
serverrec中需添加2项allocated_drive, mount_index

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#266]
- `allocated_drive`:
  这一项表示被集群管理的磁盘,可以被block group coordinator分配block上去.

  `make_serverrec` 时, 如果发现有`/xec/dirve/00*` 存在但不在allocated_drive中的**mount**点的磁盘, 自动加入. 让系统直接使用. (**只添加,不删除, 删除由管理员触发**)

  这里和s2的逻辑不一样了, s2里必须由管理员添加磁盘. 这里现在设计成自动添加.

- `next_mount_index`: 用于记录下次mount磁盘时使用的drive_index数字, `00*`里面的这个数字, 初始化时, 设置为1, 表示下次mount的drive是`001`, 每次mount磁盘要加1. 避免使用重复的`drive_index`.

- 格式:

```
{
  ...
  "next_mount_index": 1,
  "allocated_drive": {
     "001": { "status": "readonly|normal", },
     "002": { "status": "readonly|normal", },
  }
}
```

**Comment by drmingdrmer** [comment]
@liubaohai @sejust @breakwang @piepiper @pengsven 求看看合适不?

**Comment by pengsven** [comment]
未mount磁盘已存在的数据怎么处理

**Comment by pengsven** [comment]
未mount磁盘已存在的数据怎么处理

**Comment by drmingdrmer** [comment]
不管...
