### ISSUE TITLE
rangedict 模块

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#292]
用在多副本集群中查找对应sha1 区间的已归入ec的文件.

实现一个range对应一个值的实现. 支持2种构造方法; 继承list, 方便转json
```
class RangeDict(list)
RangeDict({
(1,2): val1,
(3,4): val2,
})

RangeDict((1,2, val1), [3,4, val2], ([5,6], val3)…)
# what’s inside rangedict: [[1,2,val1],[3,4,val2],[5,6,val3]]
```

### RangeDict.get(v): 

返回这个单值v所在的range对应的值. 没在任何range里raise KeyError.

### RangeDict.set(rng, val):

更新某个range对应的值.

```
rd = RangeDict([[1,3], 13]) # what’s inside rangedict: [[1,3,13]]
rd.set([2, 4], 24) # what’s inside rangedict: [ [1,2, 13], [2,4, 24] ]
```

参考: rangeset.

**Comment by drmingdrmer** [comment]
还没想...3copy里可以主动推送的就etcd了. 数据库的话还要加表...贼不想加表...

**Comment by liubaohai** [comment]
不太明白val有啥用，直接用rangeset感觉也行啊，如果它支持字符串的话

**Comment by drmingdrmer** [comment]
@liubaohai 是支持字符串的, 但是rangeset只能表示一个range存在与否,不能表示某个range对应的值.
类似set 和 dict的差别.
