### ISSUE TITLE
rangeset.RangeDict: 增加方法取最小值对应的range: 

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#311]
### `i, rng, val = RangeDict.get_min(is_lt=None)`: 返回具有最小value的index, range和对应的value.
最小值由参数`is_lt`定义: `is_lt(a,b)` 返回True, 如果用户认为`a<b`.

如果`is_lt` 是None, 则直接通过`a < b`的运算符判断.

返回值`rng`是一个ValueRange对象.

如果RangeDict为空,raise ValueError(参考的`min([])`的错误.)

**Comment by wenbobuaa** [comment]
@drmingdrmer 
返回值 rng 应该是个 RangeSet 吧，最小的 value 可能对应着多个不连续的 range .

**Comment by drmingdrmer** [comment]
取第一个吧~
