### ISSUE TITLE
代码调整: ec中的needle source needle referrers定义迁移到ectypes module中.

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#359]
ec里已经有test/测试了.

**Comment by hubiyong** [comment]
将原来引用ec中needle_source的部分改为引用pykit中的needle_source，并在imports2部分修改 new_needle_source 函数，增加new_needle_id_elt函数

**Comment by hubiyong** [comment]
引用和imports2部分修改在ec中新建一个issue修改
