### ISSUE TITLE
zktx.redisstorage同步zookeeper中删除的节点

### ISSUE THREAD

**Issue by myy2829** [bsc-s2/pykit#371]
zookeeper中通过zkclient.delete删除掉的节点，无法同步到redis

**Comment by drmingdrmer** [comment]
zkclient.delete是肯定无法同步的. redisstorage只能同步journal中有变化的记录.也就是通过zktx修改的zk节点.

所以...应该是修改redisstorage, 检测到journal中一个删除操作的时候, 直接删除redis里的记录,而不是留下一个标删的记录.

**Comment by drmingdrmer** [comment]
设置为NULL就是删除了...
