### ISSUE TITLE
ectypes.ServerID 修改结构: 增加 IDC信息

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#390]
### (做啥)

- 服用前: server id: 12个hex char
- 服用后: server id: `<6-char-idc-id><original-server-id-12-hex-char>`

idc-id考虑2点: 定宽和有基本的可读性(总机房不超过10个目前, 如果考虑边缘机房以后可能加入, 6个字符大概也够用了):

6个字符大致可以表示出地区和机房名称,不够6个字符用`0`补, 如石家庄: `sjz000`; 如第2个石家庄机房可能是`sjz001`; 如石家庄的金石机房: `sjzjs0`.

### (为啥)

现在在拿到server id或block id要取idc信息的时候, 必须通过读取redis/zk的server meta来取得, 贼麻烦.

希望程序在需要取得server/block的idc信息时不需要RPC调用.

在代码逻辑中脱离RPC调用取得机房信息. 但在呈现时(如manager/web portal等地方), 还需要配合配置文件里的信息提供完整可读的名字.

### (咋弄)

- ectypes 增加IDCID的数据结构.
- ectypes.ServerID 变成2个字段: idc+server
- clusterconf中增加定义  idc-id和可显示名字的对应关系:
  ```
  idc:
    sjz000: { label: ".shijiazhuang.jinshi", name: "石家庄-金石" }
    ...
  ```
- block-group中记录的idc为6char的idc-id; region中记录的idc也是.
- 修改ec repo中其他通过cluster_xx.py文件读取idc信息的地方.

**Comment by myy2829** [comment]
IDCID没有可读性也没关系吧，这是给程序用的，不是给人看的，哈？
可以用00，01，02这种表示IDCID吗，跟block index里的idc编号统一，这样block group里也不需要存block_group.idcs这个key了，怎么样呢

**Comment by drmingdrmer** [comment]
block group 里的idc可能不包含所有集群里的idc. 2个group的idc排序也可能不一样.

**Comment by drmingdrmer** [comment]
如果可读最好能可读一点. 人接受和理解信息的速度是很慢很慢的...

**Comment by myy2829** [comment]
嗯嗯

**Comment by pengsven** [comment]
么问题

**Comment by liubaohai** [comment]
所有引用serverid的是不是都需要修改啊。比如drive_id、block_id

**Comment by sejust** [comment]
没问题

**Comment by drmingdrmer** [comment]
> 所有引用serverid的是不是都需要修改啊。比如drive_id、block_id

恩. 但这2个地方都是ectypes里的, 有测试, 改起来不麻烦. 需要注意的是直接把server-id用做string的地方.

感觉...用drive id block id的地方是不太需要改的...因为传入的server id就是从str 换了个值 ,数据结构, 接口没太多变化.

**Comment by piepiper** [comment]
没问题
