### ISSUE TITLE
http module添加基于FixedKeysDict的request的结构定义

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#397]
### (做什么)

- 定义一个`class Request(dictutil.FxiedKeysDict)`, 表示一个request, 用于awssign 和 http 模块, 结构如下:

```
request = {
    'verb': 'PUT',
    'uri': '/test-bucket/test-key',
    'args': {
        'foo2': 'bar2',
        'foo1': True,
        'foo3': ['bar3', True],
    },
    'headers': {
        'Host': 'bscstorage.com',
        'Content-Length': len(file_content),
    },
    'body': file_content,
}
```

- Request 增加一个函数: `aws_sign(access_key, secret_key, query_auth=False, sign_payload=False, headers_not_to_sign=[], request_date=None, signing_date=None, region=None, service=None, expires=None)`, 用来将当前request实例进行aws格式的签名. 参考`pykit.awssign`

**Comment by hubiyong** [comment]
在class Singer中init函数中有region和service参数，用来构造credential_scope，而credential_scope又是返回的ctx字典中的元素，所以这个aws_sign()函数里面需要这两个参数吗？ @drmingdrmer

**Comment by drmingdrmer** [comment]
嗯. 需要.

**Comment by hubiyong** [comment]
好的，我在issue上加上去了。

**Comment by hubiyong** [comment]
Request类里面需要添加一个send_request()接口发送POST和GET请求的吗？
