### ISSUE TITLE
fsutil.cat stat file 特别耗ioutil

### ISSUE THREAD

**Issue by sejust** [bsc-s2/pykit#400]
### (做什么)

减少log_collector.py (fsutil.cat)的IO消耗

### (为什么要做)

目前日志磁盘（系统盘） ioutil 一直90-100%

### (使用什么工具)

无

### (实现思路)

研究下文件操作，做相关优化

**Comment by drmingdrmer** [comment]
stat file操作很多吗? 在使用的过程中?
