### ISSUE TITLE
ectypes.DriveID 增加1个属性port, 整数类型, 表示这个drive所在blockserver的port

### ISSUE THREAD

**Issue by drmingdrmer** [bsc-s2/pykit#415]
### (做什么)

- ectypes.DriveID 增加1个属性port, 整数类型, 表示这个drive所在blockserver的port;
- pykit.config 增加1个配置项: ectypes_base_port 默认是6000, 替代ec里的cluster_block.blocksvr_base_port
- 去掉ec里的./cluster_block.py: get_port() 函数

### (为什么要做)

方便从blockid, drive id等信息里直接取端口.

### (实现思路)

增加port属性, 跟mountpoint_index使用同样的start/end:

```python
class DriveID(IDBase):

    _attrs = (
        ('server_id', 0, 18, ServerID),
        ('_padding_0', 18, 19, _padding_0),
        ('mountpoint_index', 19, 22, MountPointIndex),
    )

    _str_len = 22

    _tostr_fmt = '{server_id}0{mountpoint_index:0>3}'

```

**Comment by LvTing123** [comment]
增加port属性后，为什么和mountpoint_index使用同样的start/end呢？19-22已经表示mountpoint_index了呀

**Comment by drmingdrmer** [comment]
port和mountpoint_index都是从19-22这段信息中提取出来的.
